---
title: "Ejercicios tema 6"
author: "Alejandro Ríos"
date: "9/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Tablas a partir de dataframes

Leemos el archivo EnergyDrink de la carpeta data
```{r}
Beb_Energ = read.table("../data/EnergyDrink", header = TRUE)
str(Beb_Energ)
head(Beb_Energ, 5)
summary(Beb_Energ)
```
Tablas en dataframes
```{r}
#tabla de frecuencias absolutas por columna
apply(Beb_Energ, MARGIN = 2, FUN = table)

#solo a una columna
table(Beb_Energ$estudio)

#table del data frame completo
table(Beb_Energ)

#table de algunas columnas
table(Beb_Energ[c(1, 3)])

#flat table
ftable(Beb_Energ, col.vars = 2)
```

### Gráficos de barras
```{r}
#Gráfico de barras de la columna sexo de frecuencias absolutas
barplot(table(Beb_Energ$sexo), col=c("lightblue", "pink"), main = "Diagrama de barras\n de las frecuencias absolutas\n de a variable \"Sexo\"")

#Gráfico de barras de la columna sexo de frecuencias relativas
barplot(prop.table(table(Beb_Energ$sexo)), col=c("lightblue", "pink"), main = "Diagrama de barras\n de las frecuencias relativas\n de a variable \"Sexo\"")
```
Más ejemplos de gráficos de barras
```{r}
par(mfrow=c(1, 2))
barplot(table(Beb_Energ$bebe), col = c("green"))
barplot(table(Beb_Energ$bebe), col = c("red", "blue"), horiz = TRUE)
```

Gráfico de barras de columnas apliladas y una al lado de la otra
```{r}
par(mfrow=c(1, 2))

barplot(table(Beb_Energ[c(2, 3)]), legend.text = TRUE)

barplot(table(Beb_Energ[c(2, 3)]), legend.text = c("No", "Yes"), beside = TRUE, names = c("Men", "Women"), col = c("yellow", "lightblue"))
```

### Gráfico circular (pie)
```{r}
pie(table(Beb_Energ$estudio), main="Diagrama circular estudio")
```
### Gráfico de mosaico
```{r}
#Usando plot
plot(table(Beb_Energ$sexo, Beb_Energ$bebe), main="Gráfico de mosaico de las variables \n\"Sexo\" y \"Bebe\"")

#Para 3 variables
plot(table(Beb_Energ$estudio, Beb_Energ$bebe, Beb_Energ$sexo), main="Gráfico de mosaico Bebe bebidas energéticas", col=c("lightblue", "pink"))
```

### Prueba paquete vcd
```{r}
library(vcd)
cotabplot(HairEyeColor)
```

