---
title: "Datos ordinales"
author: "Alejandro Ríos"
date: "9/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Estadística descriptiva con datos ordinales
Ejemplo con encuesta de 5 niveles
```{r}
set.seed(2018)
clientes = sample(1:5, 50, replace = TRUE)
clientes
set.seed(NULL)
#Frecuencias absolutas acumuladas
cumsum(table(clientes))
#Frecuencias relativas acumuladas
cumsum(prop.table(table(clientes)))
```

Ejemplo con notas
```{r}
notas = sample(c("S", "A", "N", "Ex"), 100, replace = TRUE)
notas = ordered(notas, levels = c("S", "A", "N", "Ex"))

fAbs = table(notas)

barplot(fAbs, main = "Frecuencias absolutas", ylim = c(0, 50))

#Frecuencias absolutas acumuladas
cumsum(fAbs)

#Frecuencias relativas acumuladas
cumsum(prop.table(fAbs))

barplot(cumsum(prop.table(fAbs)), main = "Frec. rel. acum.", ylim=c(0, 1))


```

Ejemplo cuellos jirafas
```{r}
longitud = sample(c("Muy.corto", "Corto", "Normal", "Largo", "Muy.largo"), 100, replace = TRUE)
longitud = ordered(longitud, levels = c("Muy.corto", "Corto", "Normal", "Largo", "Muy.largo"))

Fr.Abs = table(longitud)
Fr.Abs

Fr.Rel = prop.table(Fr.Abs)
Fr.Rel

Fr.Acum = cumsum(Fr.Abs)
Fr.Acum

Fr.RAcum = cumsum(Fr.Rel)
Fr.RAcum                   

barplot(Fr.RAcum, main = "Diagrama frec. rel. acum.", ylim = c(0, 1))
```

Ejemplo jirafas por zona
```{r}
zonas = sample(c("A", "B", "C", "D"), 100, replace = TRUE)
zonas = ordered(zonas, levels = c("A", "B", "C", "D"))

#hacemos dataframe
jirafas = data.frame(zonas, longitud)
head(jirafas)
str(jirafas)

#Frecuancias acumuladas
t(apply(table(jirafas), MARGIN = 1, FUN = cumsum))

#frecuencias relativas
t(apply(prop.table(table(jirafas), margin = 1), MARGIN = 1, FUN = cumsum))

#Gráfico de barras
diagrama = apply(prop.table(table(jirafas), margin = 1), MARGIN = 1, FUN = cumsum)
barplot(diagrama, beside = TRUE, legend = TRUE, main = "Diagrama de barras de \n frecuencias relativas acumuladas de longitudes por zonas", args.legend = list(x="topleft", cex=0.55))
```

Ejemplo con dataframe "datacrab"
```{r}
crabs = read.table("../../data/datacrab.txt", header = TRUE)
crabs = crabs[, -1] #omitir la primera columna
str(crabs)

#intervalos
intervalos = cut(crabs$width, breaks = c(21, 25, 29, 33, Inf), right = FALSE, labels = c("21-25", "25-29", "29-33", "33-..."))

#agregamos los intervalos al data frame
crabs$width.rank = ordered(intervalos)
str(crabs)

tabla_1 = table(crabs[, c(1,6)])

Fr.rel = round(prop.table(tabla_1, margin = 1), 3)
Fr.rel

Fr.rel.acu = round(apply(prop.table(tabla_1, margin = 1), MARGIN = 1, FUN = cumsum), 3)
Fr.rel.acu


```


