---
title: "Prueba R y Python con Reticulate"
author: "Alejandro Ríos"
date: "8/9/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reticulate
```{r}
library(reticulate)
use_python("/Users/arios/anaconda3/bin/python3")
os <- import("os")
os$listdir(".")
```
```{r pruebaNumpy}
np <- import("numpy", convert=FALSE) #no convierte objetos por defecto
x <- np$array(c(1:4))
sum <- x$cumsum()
print(sum)
py_to_r(sum) #convierte a variable de r
print(sum)
```
## Ayuda
```{r pruebaPandas}
pd <- import("pandas")
#py_help(pd$DataFrame) #para ver ayuda de alguna función de paquete de python
```
## Arreglos (usando función de reticulate)
```{r}
a <- np_array(c(1:10), order="C")
a
```

```{r transDFaPy}
datos <- iris
head(datos)
datos_py = r_to_py(datos) #transformar a datos de python
```
```{python}
import numpy as np
import pandas as pd
type(r.datos_py)
r.datos_py.head()
```

##Sparse matrix
```{r}
library(Matrix)
N <- 6
set.seed(123)
sparse_mat <- sparseMatrix(
  i = sample(N, N, replace = F),
  j = sample(N, N, replace = F),
  x = runif(N),
  dims = c(N, N)
)
sparse_mat
```






